#!/bin/sh

#
#  Configuration.default
#

#
#  If the MGICONFIG environment variable does not have a local override,
#  use the default "live" settings.
#
if [ "${MGICONFIG}" = "" ]
then
    MGICONFIG=/usr/local/mgi/live/mgiconfig
    export MGICONFIG
fi

. ${MGICONFIG}/master.config.sh

MGI_JAVALIB=${DBSNPLOAD}/lib/java
export MGI_JAVALIB
