#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`

. ./Configuration

$ANT buildall
unlink ../core.jar
unlink ${MGI_JAVALIB}/core.jar
ln -s ${MGI_JAVALIB}/lib_java_core/core.jar ${MGI_JAVALIB}/core.jar
