#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`

. ./Configuration

$ANT buildall
unlink ${DBSNPLOAD}/lib/java/core.jar
ln -s ${DBSNPLOAD}/lib/java/lib_java_core/core.jar ${DBSNPLOAD}/lib/java/core.jar
