#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`
cp ./Configuration.default Configuration
. ./Configuration

$ANT buildall
